(function(){
const SUPABASE_URL="https://ucehhsythixyvhrzwlth.supabase.co";
const SUPABASE_KEY="sb_publishable_bK03-qntjRlai8Q7yybHzw_JYn3FQrC";
window.rkdSupabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const sb=window.rkdSupabase;
window.escapeHtml=function(value){return String(value==null?"":value).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/\x27/g,"&#39;");};
window.rkdCloud={
 async user(){const r=await sb.auth.getUser();return r.data.user||null},
 async requireUser(){const u=await this.user();if(!u)throw new Error("Please log in first.");return u},
 async getSettings(){const {data,error}=await sb.from("site_settings").select("*").eq("id","site").maybeSingle();if(error)throw error;const d=data&&data.data?data.data:{};return Object.assign({id:data?.id||null},d,{profilePhoto:d.profilePhoto||d.profile_photo_url||"",coverPhoto:d.coverPhoto||d.cover_photo_url||"",heroCopy:d.heroCopy||d.hero_copy||"",aboutSecond:d.aboutSecond||d.about_second||""})},
 async saveSettings(v){await this.requireUser();const old=await this.getSettings();const data={eyebrow:v.eyebrow??old.eyebrow??"",title:v.title??old.title??"",heroCopy:v.heroCopy??old.heroCopy??"",name:v.name??old.name??"",role:v.role??old.role??"",about:v.about??old.about??"",aboutSecond:v.aboutSecond??old.aboutSecond??"",email:v.email??old.email??"",phone:v.phone??old.phone??"",profilePhoto:v.profilePhoto??old.profilePhoto??"",coverPhoto:v.coverPhoto??old.coverPhoto??""};const {data:row,error}=await sb.from("site_settings").upsert({id:"site",data,updated_at:new Date().toISOString()},{onConflict:"id"}).select().single();if(error)throw error;return row},
 async getBooks(){const {data,error}=await sb.from("books").select("*").order("id",{ascending:true});if(error)throw error;return (data||[]).map(this.mapBook)},
 async seedBooks(list){await this.requireUser();if(!list||!list.length)return;const rows=list.map(b=>({title:b.title||"Untitled",author:b.author||"Rahul Kumar Das",price:Number(b.price||0),category:b.category||"General / Other",description:b.desc||"",sample_pages:b.samplePages||"",amazon:b.amazon||"",buy_link:b.buyLink||"",cover_url:b.cover||"",pdf_path:b.pdf||"",pdf_name:b.pdfName||"",status:b.status||"Published",is_new:!!b.new}));const {error}=await sb.from("books").insert(rows);if(error)throw error},
 mapBook(b){return {id:b.id,title:b.title,author:b.author,price:Number(b.price||0),category:b.category,desc:b.description||"",samplePages:b.sample_pages||"",amazon:b.amazon||"",buyLink:b.buy_link||"",cover:b.cover_url||"",pdf:b.pdf_path||null,pdfName:b.pdf_name||"",status:b.status||"Published",new:!!b.is_new}},
 async saveBook(b,id){await this.requireUser();let old={};if(id){const q=await sb.from("books").select("*").eq("id",id).single();if(q.error)throw q.error;old=this.mapBook(q.data)}const row={title:b.title??old.title??"Untitled",author:b.author??old.author??"Rahul Kumar Das",price:(b.price!==undefined&&b.price!=="")?Number(b.price):Number(old.price||0),category:b.category??old.category??"General / Other",description:b.desc??old.desc??"",sample_pages:b.samplePages??old.samplePages??"",amazon:b.amazon??old.amazon??"",buy_link:b.buyLink??old.buyLink??"",cover_url:(b.cover||old.cover||""),pdf_path:(b.pdf||old.pdf||""),pdf_name:(b.pdfName||old.pdfName||""),status:b.status??old.status??"Published",is_new:b.new!==undefined?!!b.new:!!old.new,updated_at:new Date().toISOString()};const r=id?await sb.from("books").update(row).eq("id",id).select().single():await sb.from("books").insert(row).select().single();if(r.error)throw r.error;return r.data},
 async deleteBook(id){await this.requireUser();const {error}=await sb.from("books").delete().eq("id",id);if(error)throw error},
 async upload(file,folder){await this.requireUser();if(!file)throw new Error("No file selected.");const safe=file.name.toLowerCase().replace(/[^a-z0-9._-]+/g,"-");const path=folder+"/"+Date.now()+"-"+safe;const {error}=await sb.storage.from("website-media").upload(path,file,{upsert:true,contentType:file.type||undefined});if(error)throw error;const {data}=sb.storage.from("website-media").getPublicUrl(path);return data.publicUrl},
 async getPhotos(){const {data,error}=await sb.from("website_photos").select("*").order("id",{ascending:false});if(error)throw error;return (data||[]).filter(p=>p.image_url)},
 async savePhoto(p){await this.requireUser();if(!p.image)throw new Error("Photo URL is missing.");const {data,error}=await sb.from("website_photos").insert({title:p.title||"",category:p.category||"Other",image_url:p.image,file_name:p.fileName||""}).select().single();if(error)throw error;return data},
 async deletePhoto(id){await this.requireUser();const {error}=await sb.from("website_photos").delete().eq("id",id);if(error)throw error}
};
})();